#!/bin/sh
# dieses bash-Skript konvertiert das englische UDO-Handbuch nach ST-Guide
# this bash scripts converts the english UDO Manual to ST-Guide
udo --stg --verbose --force-long -D LANG_EN manual.u -o manual-en.stg
