#!/bin/sh
# dieses bash-Skript konvertiert das englische UDO-Handbuch nach RTF (Rich Text Format)
# this bash script converts the english UDO Manual to RTF (Rich Text Format)
udo --rtf --verbose --force-long -D LANG_DE --tree -o manual-en.rtf manual.u $*
