#!/bin/sh
# dieses bash-Skript konvertiert das englische UDO-Handbuch nach WinHelp-Source
# this bash scripts converts the english UDO Manual to WinHelp-Source
udo --win --verbose --force-long -D LANG_EN --tree -o ../win-en/manual-en.rtf manual.u $*