#!/bin/sh
# dieses bash-Skript konvertiert das UDO-Handbuch in Englisch nach NROFF
# this bash script converts the english UDO Manual to NROFF
udo --nroff --verbose --force-long -D LANG_EN manual.u -o manual-en.nroff