#!/bin/sh
# dieses bash-Skript konvertiert das deutsche UDO-Handbuch nach GNU-texinfo
# this bash script converts the german UDO Manual to GNU-texinfo
udo --info --verbose --force-long -D LANG_DE --tree -o manual-de.info manual.u $*
