#!/bin/sh
# dieses bash-Skript konvertiert das englische UDO-Handbuch nach LaTeX
# this bash scripts converts the english UDO Manual to LaTeX
udo --tex --verbose --force-long -D LANG_EN manual.u -o manual-en.tex
