#!/bin/sh
# dieses bash-Skript konvertiert das deutsche UDO-Handbuch nach ASCII (text)
# this bash script converts the german UDO Manual to ASCII (text format)
udo --asc --verbose --force-long -D LANG_DE manual.u -o manual-de.txt