###########################################################
# @(#) Makefile fuer IRIX
# @(#) Dirk Hagedorn, 27.06.1996
###########################################################
CC = gcc 
CFLAGS = -g -O2 -Wall -D__IRIX__

LDFLAGS = -s

include makefile.in

