###########################################################
# @(#) Makefile fuer EMX-GCC und GNU-Make oder dmake
# @(#) Dirk Hagedorn, 27.06.1996
###########################################################
CC = gcc
O=.o
X=

CFLAGS = -O2 -Wall -D__MSDOS__

LDFLAGS = 

include makefile.in


udo$(X):	$(OSRC) cli$(O)
		$(CC) $(CFLAGS) $(OSRC) cli$(O) $(LDFLAGS) -o $@
