#!/bin/sh
export UDOINPUTPATH=/usr/share/udo/udoinput/
ddd ../../UDO/Source/udo
# --html --verbose --force-long --tree --check
# -o ../../HTML-Out/bergpano/index.html bergpano.txt
chmod 644 ../../HTML-Out/bergpano/*.html
mv ../../HTML-Out/bergpano/index.ulh .
mv ../../HTML-Out/bergpano/index.uth .
