#!/bin/sh
# dieses bash-Skript konvertiert das deutsche UDO-Handbuch nach HTML
# this bash script converts the german UDO Manual to HTML
udo --html --verbose --force-long -D LANG_DE --tree -o ../html-de/index.html manual.u $*
mv ../html-de/index.ulh ../manual-de.ulh
mv ../html-de/index.uth ../manual-de.uth
