###########################################################
# @(#) Makefile fuer Amiga (mit amigcc)
# @(#) Dirk Hagedorn, 05.08.1998
###########################################################
CC = amigcc

CFLAGS = -g -O2 -Wall -D__AMIGA__

#CFLAGS =	-g -O2 -D__AMIGA__ \
#-Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations \
#-Wshadow -Wwrite-strings -Wbad-function-cast -Wcast-qual \
#-Wconversion -pedantic 

LDFLAGS = -s

include makefile.in
