###########################################################
# @(#) Makefile fuer HP-UX, ISO-Latin-1, HP make
# @(#) Dirk Hagedorn, 30.07.1996
###########################################################

CC =	gcc

CFLAGS =	-g -O2 -D__HPUX_ISO__ -Wall

#CFLAGS =	-g -O2 -D__HPUX_ISO__ \
#-Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations \
#-Wshadow -Wwrite-strings -Wbad-function-cast -Wcast-qual \
#-Wconversion -pedantic 

LDFLAGS =	-lgcc

include makefile.in

