###########################################################
# @(#) Makefile fuer Sinix
# @(#) Dirk Hagedorn, 27.06.1996
###########################################################
CC = cc 
CFLAGS = -g -O2 -W2 -D__SINIX__

LDFLAGS =

include makefile.in

