###########################################################
# @(#) Makefile fuer NeXTStep
# @(#) Dirk Hagedorn, 30.07.1996
###########################################################
CC = cc 
O=.o
X=

CFLAGS = -O2 -Wall -D__NEXTSTEP__

LDFLAGS = 

include makefile.in


udo$(X):	$(OSRC) cli$(O)
		$(CC) $(CFLAGS) $(OSRC) cli$(O) $(LDFLAGS) -o $@
