###########################################################
# @(#) Makefile fuer DJGPP-Cross-Compiler (mit gcc-go32)
# @(#) Dirk Hagedorn, 26.12.1998
###########################################################
CC = gcc-go32

CFLAGS = -g -O2 -Wall -D__MSDOS__

#CFLAGS =	-g -O2 -D__MSDOS__ \
#-Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations \
#-Wshadow -Wwrite-strings -Wbad-function-cast -Wcast-qual \
#-Wconversion -pedantic 

LDFLAGS = -s

include makefile.in
