###########################################################
# @(#) Makefile fuer SunOS
# @(#) Dirk Hagedorn, 27.06.1996
###########################################################
CC = gcc 
CFLAGS = -g -O2 -Wall -D__SUNOS__

LDFLAGS = -s

include makefile.in

